version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs
      - pip install mkdocs-material
      - pip install mkdocs-material-extensions

mkdocs:
  configuration: mkdocs.yml